<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\SsePulse.Client.Extensions.Stores.Mongo\SsePulse.Client.Extensions.Stores.Mongo.csproj" />
        <ProjectReference Include="..\SsePulse.Client.Tests.Common\SsePulse.Client.Tests.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.msbuild">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
        <PackageReference Include="MongoDB.Driver" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>
</Project>

