version: 2
updates:
  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    commit-message:
      prefix: "chore(dependencies)"
    labels:
        - "dependencies"

  - package-ecosystem: "nuget"
    directories:
      - "/"
      - "/src"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    commit-message:
      prefix: "chore(dependencies)"
    labels:
      - "dependencies"