[remote.github]
owner = "claudiom248"
repo = "ssepulse.client"

[changelog]
header = ""
body = """
## What's Changed
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% macro print_commit(commit) -%}
    - {% if commit.scope %}**`{{ commit.scope }}`** — {% endif %}\
        {% if commit.breaking %}[**breaking**] {% endif %}\
        {{ commit.message | upper_first }}\
{% endmacro -%}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits
    | filter(attribute="scope")
    | unique(attribute="message")
    | sort(attribute="scope") %}
    {{ self::print_commit(commit=commit) }}
{%- endfor %}
{% for commit in commits | unique(attribute="message") %}
    {%- if not commit.scope -%}
        {{ self::print_commit(commit=commit) }}
    {% endif -%}
{% endfor -%}
{% endfor -%}
{%- if github -%}
{% if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
## New Contributors ❤️
{% endif %}\
{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
  * @{{ contributor.username }} made their first contribution
    {%- if contributor.pr_number %} in \
      [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}) \
    {%- endif %}
{%- endfor -%}
{%- endif %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
filter_commits = false
topo_order = false
sort_commits = "newest"
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->🚀 Features" },
    { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
    { message = "^perf", group = "<!-- 2 -->⚡ Performance" },
    { message = "^refactor", group = "<!-- 3 -->🚜 Refactor" },
	{ message = "^doc", group = "<!-- 4 -->📚 Documentation" },
	{ message = "^chore", group = "<!-- 5 -->🔧 Maintenance" },
	{ message = "^Merge tag", skip = true },
    { message = "^Merge tag", skip = true },
    { message = "^Merge pull request", skip = true },
    { message = ".*", skip = true },
]
