<?xml version="1.0" encoding="utf-8"?>
<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))"/>
    <PropertyGroup>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemDefinitionGroup>
        <ProjectReference>
            <AdditionalProperties>$(AdditionalProperties);TreatWarningsAsErrors=false;EnforceCodeStyleInBuild=false;RunAnalyzersDuringBuild=false;GenerateDocumentationFile=false</AdditionalProperties>
        </ProjectReference>
    </ItemDefinitionGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" PrivateAssets="all" />
        <AdditionalFiles Include="$(MSBuildThisFileDirectory)BannedSymbols.txt" />
    </ItemGroup>
</Project>



