<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <PackageId>SsePulse.Client.Hosting</PackageId>
        <Description>Provides a hosted service for consuming events from SseSource, and extension methods for registering it.</Description>
        <PackageTags>hosting;dependency-injection;server-sent-events;sse;sse-consumer;sse-stream;ssepulse;ssepulse-client;client</PackageTags>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SsePulse.Client.DependencyInjection\SsePulse.Client.DependencyInjection.csproj" />
      <ProjectReference Include="..\SsePulse.Client\SsePulse.Client.csproj" />
    </ItemGroup>


    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    </ItemGroup>

</Project>
